routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\TransaksiController;
use App\Http\Controllers\MasterBarangController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AuthController;

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index']);

Route::group(['middleware' => ['guest']], function () {
	Route::get('/signin', 	[AuthController::class, 'loginView'])->name('login');
	Route::post('/signin', 	[AuthController::class, 'login']);

	Route::get('/signup', 	[AuthController::class, 'registerView']);
	Route::post('/signup',	[AuthController::class, 'register']);

});
Route::group(['middleware' => ['auth']], function () {
    Route::get('/', [HomeController::class, 'index']);

    Route::resource('/barang', MasterBarangController::class)->middleware('admin');
    Route::post('/barang/search', [MasterBarangController::class, 'search']);

    Route::resource('/user', UserController::class)->middleware('admin');

    Route::get('/transaksi/input', [TransaksiController::class, 'index']);
    Route::post('/transaksi', [TransaksiController::class, 'store']);
    Route::get('/transaksi', [TransaksiController::class, 'show_all_pembelian']);
    Route::post('/transaksi/search', [TransaksiController::class, 'search']);
    Route::get('/transaksi/{id}', [TransaksiController::class, 'show_detail_pembelian']);
    Route::get('/transaksibarang/{id}', [TransaksiController::class, 'getbarang'])->name('transaksibarang');

    Route::get('faktur/{id}', [TransaksiController::class, 'cetak_pdf']);

    Route::post('/logout', [AuthController::class, 'logout']);
    Route::get('/logout',  [AuthController::class, 'logout']);

});

app/Models/TransaksiPembelian.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
// use Illuminate\Support\Carbon;
use Carbon\Carbon;


class TransaksiPembelian extends Model
{
    use HasFactory;
    protected $guarded = ['id'];
    protected $table = 'transaksi_pembelian';

    public function transaksi_pembelian_barang(){
    	return $this->hasMany(TransaksiPembelianBarang::class);
    }
    public function getDateDisplayAttribute()
    {
        return Carbon::parse($this->attributes['created_at'])->translatedFormat('l, d F Y H:i');
    }
    public function getHariDisplayAttribute(){
        return Carbon::parse($this->attributes['created_at'])->translatedFormat('l');
    }
    public function getTanggalDisplayAttribute(){
        return Carbon::parse($this->attributes['created_at'])->translatedFormat('d/m/Y');
    }
    public function getJamDisplayAttribute(){
        return Carbon::parse($this->attributes['created_at'])->translatedFormat('H:i');
    }
}

app/Http/Controllers/TransaksiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use \App\Models\MasterBarang;
use \App\Models\TransaksiPembelian;
use Illuminate\Support\Facades\DB;
use \App\Models\TransaksiPembelianBarang;
use PDF;

class TransaksiController extends Controller
{
    public function index(){
        $barang = MasterBarang::where('isActive',1)->get();
        if (auth()->user()->isAdmin == 0) {
            $tp = TransaksiPembelian::where('created_at','like','%'.date("Y-m-d").'%')->latest()->first();
        } else {
            $tp = TransaksiPembelian::latest()->first();
        }

        // $tp = TransaksiPembelian::latest()->first();

        if ($tp == null) {
            return view('transaksi.input',compact('barang'));
        }
        else{
            $tpb = TransaksiPembelianBarang::with('master_barang')->where('transaksi_pembelian_id',$tp->id)->get();
            return view('transaksi.input',compact('barang','tp','tpb'));
        }

    }
    public function getbarang(Request $request,$id){
        $barang = MasterBarang::where('id',$id)->get();
        return response()->json($barang);
    }
    public function store(Request $request){
        $rules= [
            'total_harga'      => 'required',

        ];
        $messages = [
            'total_harga.required'        => 'Tidak ada barang yang dibeli',
        ];
        $this->validate($request,$rules,$messages);

        if ($request['jumlah']) {

            $data = new TransaksiPembelian();
            $data->total_harga = $request->total_harga;
            $data->save();

            $last = TransaksiPembelian::select('id')->orderBy('created_at','desc')->first();
            $lastId = $last->id;
            for($i=0 ; $i < count($request['jumlah']) ;$i++){
                $input = new TransaksiPembelianBarang();
                $input->transaksi_pembelian_id = $lastId;
                $input->master_barang_id = $request->master_barang_id[$i];
                $input->harga_satuan = $request->harga_satuan[$i];
                $input->jumlah = $request->jumlah[$i];
                $status=$input->save();
            }
            if($status){
                return redirect('/transaksi/input')->with('success','Data Berhasil Disimpan!');
            }else{
                return redirect('/transaksi/input')->with('error','Data Gagal Disimpan!');
            }
        }else{
            return redirect('/transaksi/input')->with('error','Data Gagal Disimpan!');
        }

    }
    public function show_all_pembelian()
    {   if (auth()->user()->isAdmin == 1) {
            $history = TransaksiPembelian::all()->sortByDesc('created_at');
        }else{
            $history = TransaksiPembelian::where('created_at','like','%'.date("Y-m-d").'%')->get()->sortByDesc('created_at');
        }

        return view('transaksi.index',compact('history'));
    }
    public function show_detail_pembelian($id)
    {
        $tp = TransaksiPembelian::find($id);
        $tpb = TransaksiPembelianBarang::with('master_barang')->where('transaksi_pembelian_id',$id)->get();
        return view('transaksi.detail',compact('tp','tpb'));
    }
    public function search(Request $request)
    {
        $harga_min = $request->harga_min;
        $harga_max = $request->harga_max;

        if (auth()->user()->isAdmin == 1) {
            if ($harga_min < $harga_max) {
                $history = TransaksiPembelian::where('total_harga','>=',$harga_min,'and')->where('total_harga','<=',$harga_max)->get()->sortBy('total_harga');
            }else if ($harga_min > $harga_max) {
                $history = TransaksiPembelian::where('total_harga','<=',$harga_min,'and')->where('total_harga','>=',$harga_max)->get()->sortByDesc('total_harga');
            }else{
                $history = TransaksiPembelian::where('total_harga','=',$harga_min,'and')->where('total_harga','=',$harga_max)->get()->sortByDesc('created_at');
            }
        }else{
            if ($harga_min < $harga_max) {
                $history = TransaksiPembelian::where('created_at','like','%'.date("Y-m-d").'%','and')->where('total_harga','>=',$harga_min,'and')->where('total_harga','<=',$harga_max)->get()->sortBy('total_harga');
            }else if ($harga_min > $harga_max) {
                $history = TransaksiPembelian::where('created_at','like','%'.date("Y-m-d").'%','and')->where('total_harga','<=',$harga_min,'and')->where('total_harga','>=',$harga_max)->get()->sortByDesc('total_harga');
            }else{
                $history = TransaksiPembelian::where('created_at','like','%'.date("Y-m-d").'%','and')->where('total_harga','=',$harga_min,'and')->where('total_harga','=',$harga_max)->get()->sortByDesc('created_at');
            }
        }


        // $history = TransaksiPembelian::where('total_harga','>=',$harga_min,'and')->where('total_harga','<=',$harga_max)->get();

        return view('transaksi.index',compact('history'));
    }
    public function cetak_pdf($id){
        set_time_limit(240);
        $tp = TransaksiPembelian::find($id);
        $tpb = TransaksiPembelianBarang::with('master_barang')->where('transaksi_pembelian_id',$id)->get();
        // return view('transaksi.pdf',compact('tp','tpb'));

        $pdf   = PDF::loadview('transaksi.pdf',compact('tp','tpb'));
        return $pdf->stream('cetak-pdf-transaksi-'.$id.'.pdf');
    }
}

resources/views/transaksi/detail.blade.php
@extends('master')
@section('title','Detail')
@section('content')

<div class="card shadow mb-4">
    <div class="card-header py-3 bg-primary d-sm-flex align-items-center justify-content-between">
        <h6 class="h5 m-0 font-weight-bold text-gray-100">Detail Pembelian</h6>
        <div class="d-inline-block">
            <a href="{{ url('transaksi') }}" class="btn btn-danger shadow-sm"><i class="fa fa-chevron-circle-left"></i> Back</a>
            {{-- <button href="#add" data-toggle="modal" data-target="#cetakModal" class="btn btn-sm btn-secondary shadow-sm"><i class="fa fa-print"></i> Export</button>
            <small class="text-gray-300">{{$p->kode_masuk}}</small> --}}
        </div>
    </div>
    <div class="card-body">
        <div class="table-responsive">
        <table class="table text-gray-800" width="100%" cellspacing="0">
            <thead>
                <tr>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="4">ID Pembelian</td>
                    <td>:</td>
                    <td>{{$tp->id}}</td>
                </tr>
                <tr>
                    <td colspan="4">Hari</td>
                    <td>:</td>
                    <td>{{$tp->hari_display}}</td>
                </tr>
                <tr>
                    <td colspan="4">Tanggal</td>
                    <td>:</td>
                    <td>{{$tp->tanggal_display}}</td>
                </tr>
                <tr>
                    <td colspan="4">Jam</td>
                    <td>:</td>
                    <td>{{$tp->jam_display}}</td>
                </tr>
                <tr>
                    <td colspan="4">Total Harga</td>
                    <td>:</td>
                    <td>{{$tp->total_harga}}</td>
                </tr>
            </tbody>
        </table>

        </div>
    </div>
</div>
<div class="card shadow mb-4">
    <div class="card-header py-3 bg-primary d-sm-flex align-items-center justify-content-between">
        <h6 class="h5 m-0 font-weight-bold text-gray-100">List Barang</h6>
        <div class="d-inline-block">

        </div>
    </div>
    <div class="card-body">
        <div class="table-responsive">
        <table class="table table-hover" id="dtprod" width="100%" cellspacing="0">
            <thead>
            <tr>
                <th>#</th>
                <th>ID</th>
                <th>Nama Barang</th>
                <th>Harga Jual</th>
                <th>QTY</th>
                <th>Subtotal</th>
            </tr>
            </thead>
            @php
                $totalakhir = 0;
            @endphp
            <tbody>
                @foreach ($tpb as $item)
                <tr>
                    <td>{{ !empty($i) ? ++$i : $i = 1 }}</th>
                    <td>{{ $item->master_barang_id }}</td>
                    <td>{{ $item->master_barang->nama_barang }}</td>
                    <td>{{ $item->harga_satuan}}</td>
                    <td>{{ $item->jumlah }}</td>
                    <td>{{ $item->jumlah*$item->harga_satuan }}</td>
                </tr>
                @php
                    $totalakhir += $item->jumlah*$item->harga_satuan;
                @endphp
                @endforeach
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="6">&nbsp;</td>
                </tr>
                <tr>
                    <td colspan="3">&nbsp;</td>
                    <td><strong>Total</strong></td>
                    <td>:</td>
                    <td>{{$totalakhir}}</td>
                </tr>
            </tfoot>
        </table>
        </div>
    </div>
</div>
<div class="d-sm-flex align-items-center justify-content-between">
    <div></div>
    <div class="d-inline-block">
        <a href="{{url("faktur/$tp->id")}}" class="btn btn-primary"><i class="fa fa-print"></i> Cetak PDF</a>
    </div>
</div>
<div>
    <br>
</div>

@endsection
{{-- @include('barang.form') --}}
@push('script')

@endpush

resources/views/transaksi/index.blade.php
@extends('master')

@section('title')
    History Transaksi
@endsection

@section('content')
@include('part.feedback')
<div class="card shadow mb-4">
    <div class="card-header py-3 bg-primary d-sm-flex align-items-center justify-content-between">
        @if (auth()->user()->isAdmin == 0)
        <h6 class="h5 m-0 font-weight-bold text-gray-100">Transaksi Hari Ini</h6>
        @else

        <h6 class="h5 m-0 font-weight-bold text-gray-100">History Transaksi</h6>
        @endif
        <div class="d-inline-block">
            <a href="{{ url('transaksi') }}" class="btn btn-sm btn-secondary shadow-sm"><i class="fa fa-redo"></i> Refresh</a>
            <a href="{{ url('transaksi/input') }}" class="btn btn-sm btn-success"><i class="fa fa-plus"></i> Tambah</a>
            {{-- <button type="button" class="btn btn-sm btn-success" data-toggle="modal" data-target="#tambahData">
                <i class="fa fa-plus"></i> Tambah
            </button> --}}
        </div>
    </div>
    <div class="card-body">
        <form method="POST" action="{{ url('/transaksi/search') }}">
            @csrf
            <div class="row">
                <div class="row col">
                    <input type="text" class="form-control col-sm-2 bg-white border-0" value="Rentang Harga" readonly>
                    <input type="number" class="form-control col" required name="harga_min">
                    <input type="text" class="form-control col-sm-2 text-center bg-white border-0" value="sampai" readonly>
                    <input type="number" class="form-control col" required name="harga_max">
                </div>
                <div class="col-sm-1">
                    <button type="submit" class="btn btn-primary">Cari</button>
                </div>
            </div>
          </form>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-hover"  width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <td>No</td>
                        <td>ID</td>
                        <td>Waktu</td>
                        <td style="display: none">Barang</td>
                        <td>Total Harga</td>
                        <td>Aksi</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach($history as $tp)
                    <tr>
                        <td>{{ !empty($i) ? ++$i : $i = 1 }}</td>
                        <td>{{ $tp->id }}</td>
                        <td>{{ $tp->date_display }}</td>
                        <td style="display: none">
                            @foreach ($tp->transaksi_pembelian_barang as $item)
                                {{ $item->master_barang->nama_barang.',' }}
                            @endforeach
                        </td>
                        <td class="text-right">Rp. {{number_format($tp->total_harga, 0 , ',', '.')}}</td>
                        <td>
                            <a href="{{ url('transaksi').'/'.$tp->id}}" class="btn btn-info"><i class="fas fa-eye"></i></a>
                            <a href="{{ url('faktur').'/'.$tp->id}}" class="btn btn-danger"><i class="fas fa-print"></i></a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection
@push('scripts')
<script>
    $(function () {
        $(".table").DataTable();
    });

</script>
@endpush

resources/views/transaksi/pdf.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Cetak PDF</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">

</head>
<body>
	<div class="container">
        <div>
            <h1 class="text-center">PDF Transaksi Pembelian</h1>
        </div>
		<table class="table table-borderless text-gray-800" width="100%" cellspacing="0">
            <tbody>
                <tr>
                    <td colspan="4">ID Pembelian</td>
                    <td>:</td>
                    <td>{{$tp->id}}</td>
                </tr>
                <tr>
                    <td colspan="4">Hari</td>
                    <td>:</td>
                    <td>{{$tp->hari_display}}</td>
                </tr>
                <tr>
                    <td colspan="4">Tanggal</td>
                    <td>:</td>
                    <td>{{$tp->tanggal_display}}</td>
                </tr>
                <tr>
                    <td colspan="4">Jam</td>
                    <td>:</td>
                    <td>{{$tp->jam_display}}</td>
                </tr>
                <tr>
                    <td colspan="4">Total Harga</td>
                    <td>:</td>
                    <td>{{$tp->total_harga}}</td>
                </tr>
            </tbody>
        </table>
        <div><br></div>
        <table class="table table-stripped" id="dtprod" width="100%" >
            <thead>
            <tr>
                <th>#</th>
                <th>ID</th>
                <th>Nama Barang</th>
                <th>Harga Jual</th>
                <th>QTY</th>
                <th>Subtotal</th>
            </tr>
            </thead>
            @php
                $totalakhir = 0;
            @endphp
            <tbody>
                @foreach ($tpb as $item)
                <tr>
                    <td>{{ !empty($i) ? ++$i : $i = 1 }}</th>
                    <td>{{ $item->master_barang_id }}</td>
                    <td>{{ $item->master_barang->nama_barang }}</td>
                    <td>{{ $item->harga_satuan}}</td>
                    <td>{{ $item->jumlah }}</td>
                    <td>{{ $item->jumlah*$item->harga_satuan }}</td>
                </tr>
                @php
                    $totalakhir += $item->jumlah*$item->harga_satuan;
                @endphp
                @endforeach
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3">&nbsp;</td>
                    <td><strong>Total</strong></td>
                    <td>:</td>
                    <td>{{$totalakhir}}</td>
                </tr>
            </tfoot>
        </table>
	</div>
</body>
</html>