routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\TransaksiController;
use App\Http\Controllers\MasterBarangController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AuthController;

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index']);

Route::group(['middleware' => ['guest']], function () {
	Route::get('/signin', 	[AuthController::class, 'loginView'])->name('login');
	Route::post('/signin', 	[AuthController::class, 'login']);

	Route::get('/signup', 	[AuthController::class, 'registerView']);
	Route::post('/signup',	[AuthController::class, 'register']);

});
Route::group(['middleware' => ['auth']], function () {
    Route::get('/', [HomeController::class, 'index']);

    Route::resource('/barang', MasterBarangController::class)->middleware('admin');
    Route::post('/barang/search', [MasterBarangController::class, 'search']);

    Route::resource('/user', UserController::class)->middleware('admin');

    Route::get('/transaksi/input', [TransaksiController::class, 'index']);
    Route::post('/transaksi', [TransaksiController::class, 'store']);
    Route::get('/transaksi', [TransaksiController::class, 'show_all_pembelian']);
    Route::post('/transaksi/search', [TransaksiController::class, 'search']);
    Route::get('/transaksi/{id}', [TransaksiController::class, 'show_detail_pembelian']);
    Route::get('/transaksibarang/{id}', [TransaksiController::class, 'getbarang'])->name('transaksibarang');

    Route::get('faktur/{id}', [TransaksiController::class, 'cetak_pdf']);

    Route::post('/logout', [AuthController::class, 'logout']);
    Route::get('/logout',  [AuthController::class, 'logout']);

});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'isAdmin'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    public function getRoleDisplayAttribute(){
        if (@$this->attributes['isAdmin'] == 1) return 'Admin';
        if (@$this->attributes['isAdmin'] == 0) return 'Kasir';
        return '-';
    }
}

resources/views/part/feedback.blade.php
@if(session('success'))
    <div class="alert with-close alert-success alert-dismissible">
        <button type="button" class="close pull-right" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {!! session('success') !!}
    </div>
@endif

@if(session('error'))
    <div class="alert with-close alert-danger alert-dismissible">
        <button type="button" class="close pull-right" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {!! session('error') !!}
    </div>
@endif

@if(count($errors) > 0)
    <div class="alert with-close alert-danger alert-dismissible">
        <button type="button" class="close pull-right" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <p>Error</p>
        <ul>
            @foreach($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/part/nav.blade.php
<nav class="navbar navbar-expand navbar-dark bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
      <i class="fa fa-bars"></i>
    </button>



    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">


      <!-- Nav Item - User Information -->
      <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{auth()->user()->name}} ( {{auth()->user()->role_display}} )</span>
          <img class="img-profile rounded-circle" src="{{ asset('img') }}/undraw_profile.svg">
        </a>
        <!-- Dropdown - User Information -->
        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in bg-danger" aria-labelledby="userDropdown">
          <a class="dropdown-item bg-danger text-white" href="{{ url('logout') }}" data-toggle="modal" data-target="#logoutModal">
            <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
            Logout
          </a>
        </div>
      </li>

    </ul>

  </nav>

resources/views/part/sidebar.blade.php
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="#">
      <div class="sidebar-brand-text">App Kasir</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    {{-- @if(auth()->user()->isAdmin == 1) --}}
    <!-- Nav Item - Dashboard -->
    <li class="nav-item">
      <a class="nav-link" href="{{ url('/') }}">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Dashboard</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">
    <div class="sidebar-heading">
        Data Management
    </div>
    <li class="nav-item">
      <a class="nav-link" href="{{ url('barang') }}">
        <i class="fas fa-fw fa-table"></i>
        <span>Barang (Admin)</span></a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{{ url('user') }}">
        <i class="fas fa-fw fa-user"></i>
        <span>User (Admin)</span></a>
    </li>
    {{-- @else --}}
    {{-- <li class="nav-item">
        <a class="nav-link" href="/profile">
        <i class="fas fa-fw fa-book"></i>
        <span>Akun</span></a>
    </li> --}}
    {{-- <li class="nav-item">
        <a class="nav-link" href="/profile">
        <i class="fas fa-fw fa-book"></i>
        <span>Profil</span></a>
    </li>
	@endif --}}

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">
    <div class="sidebar-heading">
        Transaction
    </div>
    <li class="nav-item">
        <a class="nav-link" href="{{ url('transaksi/input') }}">
        <i class="fas fa-fw fa-shopping-cart"></i>
        <span>Order</span></a>
    </li>
    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">
    <div class="sidebar-heading">
        History
    </div>
    <li class="nav-item">
        <a class="nav-link" href="{{ url('transaksi') }}">
        <i class="fas fa-fw fa-book"></i>
        <span>Transaction</span></a>
    </li>
    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">
    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
      <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

  </ul>